export const LANGUAGES = [
  { id: 'afrikaans', name: 'Afrikaans' },
  { id: 'albanian', name: 'Albanian' },
  { id: 'amharic', name: 'Amharic' },
  { id: 'arabic', name: 'Arabic' },
  { id: 'armenian', name: 'Armenian' },
  { id: 'azerbaijani', name: 'Azerbaijani' },
  { id: 'basque', name: 'Basque' },
  { id: 'belarusian', name: 'Belarusian' },
  { id: 'bengali', name: 'Bengali' },
  { id: 'bosnian', name: 'Bosnian' },
  { id: 'bulgarian', name: 'Bulgarian' },
  { id: 'catalan', name: 'Catalan' },
  { id: 'cebuano', name: 'Cebuano' },
  { id: 'chinese', name: 'Chinese (Simplified)' },
  { id: 'chinese_traditional', name: 'Chinese (Traditional)' },
  { id: 'corsican', name: 'Corsican' },
  { id: 'croatian', name: 'Croatian' },
  { id: 'czech', name: 'Czech' },
  { id: 'danish', name: 'Danish' },
  { id: 'dutch', name: 'Dutch' },
  { id: 'english', name: 'English' },
  { id: 'esperanto', name: 'Esperanto' },
  { id: 'estonian', name: 'Estonian' },
  { id: 'finnish', name: 'Finnish' },
  { id: 'french', name: 'French' },
  { id: 'frisian', name: 'Frisian' },
  { id: 'galician', name: 'Galician' },
  { id: 'georgian', name: 'Georgian' },
  { id: 'german', name: 'German' },
  { id: 'greek', name: 'Greek' },
  { id: 'gujarati', name: 'Gujarati' },
  { id: 'haitian_creole', name: 'Haitian Creole' },
  { id: 'hausa', name: 'Hausa' },
  { id: 'hawaiian', name: 'Hawaiian' },
  { id: 'hebrew', name: 'Hebrew' },
  { id: 'hindi', name: 'Hindi' },
  { id: 'hmong', name: 'Hmong' },
  { id: 'hungarian', name: 'Hungarian' },
  { id: 'icelandic', name: 'Icelandic' },
  { id: 'igbo', name: 'Igbo' },
  { id: 'indonesian', name: 'Indonesian' },
  { id: 'irish', name: 'Irish' },
  { id: 'italian', name: 'Italian' },
  { id: 'japanese', name: 'Japanese' },
  { id: 'javanese', name: 'Javanese' },
  { id: 'kannada', name: 'Kannada' },
  { id: 'kazakh', name: 'Kazakh' },
  { id: 'khmer', name: 'Khmer' },
  { id: 'kinyarwanda', name: 'Kinyarwanda' },
  { id: 'korean', name: 'Korean' },
  { id: 'kurdish', name: 'Kurdish' },
  { id: 'kyrgyz', name: 'Kyrgyz' },
  { id: 'lao', name: 'Lao' },
  { id: 'latin', name: 'Latin' },
  { id: 'latvian', name: 'Latvian' },
  { id: 'lithuanian', name: 'Lithuanian' },
  { id: 'luxembourgish', name: 'Luxembourgish' },
  { id: 'macedonian', name: 'Macedonian' },
  { id: 'malagasy', name: 'Malagasy' },
  { id: 'malay', name: 'Malay' },
  { id: 'malayalam', name: 'Malayalam' },
  { id: 'maltese', name: 'Maltese' },
  { id: 'maori', name: 'Maori' },
  { id: 'marathi', name: 'Marathi' },
  { id: 'mongolian', name: 'Mongolian' },
  { id: 'myanmar', name: 'Myanmar (Burmese)' },
  { id: 'nepali', name: 'Nepali' },
  { id: 'norwegian', name: 'Norwegian' },
  { id: 'nyanja', name: 'Nyanja (Chichewa)' },
  { id: 'odia', name: 'Odia (Oriya)' },
  { id: 'pashto', name: 'Pashto' },
  { id: 'persian', name: 'Persian' },
  { id: 'polish', name: 'Polish' },
  { id: 'portuguese', name: 'Portuguese' },
  { id: 'punjabi', name: 'Punjabi' },
  { id: 'romanian', name: 'Romanian' },
  { id: 'russian', name: 'Russian' },
  { id: 'samoan', name: 'Samoan' },
  { id: 'scots_gaelic', name: 'Scots Gaelic' },
  { id: 'serbian', name: 'Serbian' },
  { id: 'sesotho', name: 'Sesotho' },
  { id: 'shona', name: 'Shona' },
  { id: 'sindhi', name: 'Sindhi' },
  { id: 'sinhala', name: 'Sinhala (Sinhalese)' },
  { id: 'slovak', name: 'Slovak' },
  { id: 'slovenian', name: 'Slovenian' },
  { id: 'somali', name: 'Somali' },
  { id: 'spanish', name: 'Spanish' },
  { id: 'sundanese', name: 'Sundanese' },
  { id: 'swahili', name: 'Swahili' },
  { id: 'swedish', name: 'Swedish' },
  { id: 'tagalog', name: 'Tagalog (Filipino)' },
  { id: 'tajik', name: 'Tajik' },
  { id: 'tamil', name: 'Tamil' },
  { id: 'tatar', name: 'Tatar' },
  { id: 'telugu', name: 'Telugu' },
  { id: 'thai', name: 'Thai' },
  { id: 'turkish', name: 'Turkish' },
  { id: 'turkmen', name: 'Turkmen' },
  { id: 'ukrainian', name: 'Ukrainian' },
  { id: 'urdu', name: 'Urdu' },
  { id: 'uyghur', name: 'Uyghur' },
  { id: 'uzbek', name: 'Uzbek' },
  { id: 'vietnamese', name: 'Vietnamese' },
  { id: 'welsh', name: 'Welsh' },
  { id: 'xhosa', name: 'Xhosa' },
  { id: 'yiddish', name: 'Yiddish' },
  { id: 'yoruba', name: 'Yoruba' },
  { id: 'zulu', name: 'Zulu' },
];

export const PROFICIENCY_LEVELS = [
  { id: 'beginner', name: 'Beginner' },
  { id: 'elementary', name: 'Elementary' },
  { id: 'intermediate', name: 'Intermediate' },
  { id: 'advanced', name: 'Advanced' },
  { id: 'fluent', name: 'Fluent' },
];

// Sample tags - these would normally be fetched from user data
export const SAMPLE_TAGS = [
  'Greetings',
  'Common phrases',
  'Food',
  'Travel',
  'Business',
  'Family',
  'Numbers',
  'Time',
  'Weather',
  'Shopping',
  'Verbs',
  'Nouns',
  'Adjectives',
  'Vocabulary',
  'Slang',
  'Idioms',
  'Beginner',
  'Advanced'
];

export const QUIZ_TYPES = [
  { 
    id: 'translation', 
    name: 'Translation Quiz', 
    description: 'Translate phrases between languages',
    color: 'bg-primary'
  },
  { 
    id: 'multiple-choice', 
    name: 'Multiple Choice', 
    description: 'Choose the correct translation',
    color: 'bg-secondary'
  },
  { 
    id: 'listening', 
    name: 'Listening Quiz', 
    description: 'Write what you hear',
    color: 'bg-accent'
  }
];

export const QUIZ_DIFFICULTIES = [
  { id: 'easy', name: 'Easy' },
  { id: 'medium', name: 'Medium' },
  { id: 'hard', name: 'Hard' },
  { id: 'mixed', name: 'Mixed' },
];

export const QUIZ_LENGTHS = [
  { id: '5', name: '5 questions' },
  { id: '10', name: '10 questions' },
  { id: '15', name: '15 questions' },
  { id: '20', name: '20 questions' },
];

export const QUIZ_TIME_LIMITS = [
  { id: 'none', name: 'No Limit' },
  { id: '1', name: '1 Minute' },
  { id: '2', name: '2 Minutes' },
  { id: '5', name: '5 Minutes' },
  { id: '10', name: '10 Minutes' },
];
