export const LANGUAGES = [
  { id: 'af', name: 'Afrikaans' },
  { id: 'sq', name: 'Albanian' },
  { id: 'am', name: 'Amharic' },
  { id: 'ar', name: 'Arabic' },
  { id: 'hy', name: 'Armenian' },
  { id: 'az', name: 'Azerbaijani' },
  { id: 'eu', name: 'Basque' },
  { id: 'be', name: 'Belarusian' },
  { id: 'bn', name: 'Bengali' },
  { id: 'bs', name: 'Bosnian' },
  { id: 'bg', name: 'Bulgarian' },
  { id: 'ca', name: 'Catalan' },
  { id: 'ceb', name: 'Cebuano' },
  { id: 'zh-cn', name: 'Chinese (Simplified)' },
  { id: 'zh-tw', name: 'Chinese (Traditional)' },
  { id: 'co', name: 'Corsican' },
  { id: 'hr', name: 'Croatian' },
  { id: 'cs', name: 'Czech' },
  { id: 'da', name: 'Danish' },
  { id: 'nl', name: 'Dutch' },
  { id: 'en', name: 'English' },
  { id: 'eo', name: 'Esperanto' },
  { id: 'et', name: 'Estonian' },
  { id: 'fi', name: 'Finnish' },
  { id: 'fr', name: 'French' },
  { id: 'fy', name: 'Frisian' },
  { id: 'gl', name: 'Galician' },
  { id: 'ka', name: 'Georgian' },
  { id: 'de', name: 'German' },
  { id: 'el', name: 'Greek' },
  { id: 'gu', name: 'Gujarati' },
  { id: 'ht', name: 'Haitian Creole' },
  { id: 'ha', name: 'Hausa' },
  { id: 'haw', name: 'Hawaiian' },
  { id: 'he', name: 'Hebrew' },
  { id: 'hi', name: 'Hindi' },
  { id: 'hmn', name: 'Hmong' },
  { id: 'hu', name: 'Hungarian' },
  { id: 'is', name: 'Icelandic' },
  { id: 'ig', name: 'Igbo' },
  { id: 'id', name: 'Indonesian' },
  { id: 'ga', name: 'Irish' },
  { id: 'it', name: 'Italian' },
  { id: 'ja', name: 'Japanese' },
  { id: 'jv', name: 'Javanese' },
  { id: 'kn', name: 'Kannada' },
  { id: 'kk', name: 'Kazakh' },
  { id: 'km', name: 'Khmer' },
  { id: 'rw', name: 'Kinyarwanda' },
  { id: 'ko', name: 'Korean' },
  { id: 'ku', name: 'Kurdish' },
  { id: 'ky', name: 'Kyrgyz' },
  { id: 'lo', name: 'Lao' },
  { id: 'la', name: 'Latin' },
  { id: 'lv', name: 'Latvian' },
  { id: 'lt', name: 'Lithuanian' },
  { id: 'lb', name: 'Luxembourgish' },
  { id: 'mk', name: 'Macedonian' },
  { id: 'mg', name: 'Malagasy' },
  { id: 'ms', name: 'Malay' },
  { id: 'ml', name: 'Malayalam' },
  { id: 'mt', name: 'Maltese' },
  { id: 'mi', name: 'Maori' },
  { id: 'mr', name: 'Marathi' },
  { id: 'mn', name: 'Mongolian' },
  { id: 'my', name: 'Myanmar (Burmese)' },
  { id: 'ne', name: 'Nepali' },
  { id: 'no', name: 'Norwegian' },
  { id: 'ny', name: 'Nyanja (Chichewa)' },
  { id: 'or', name: 'Odia (Oriya)' },
  { id: 'ps', name: 'Pashto' },
  { id: 'fa', name: 'Persian' },
  { id: 'pl', name: 'Polish' },
  { id: 'pt', name: 'Portuguese' },
  { id: 'pa', name: 'Punjabi' },
  { id: 'ro', name: 'Romanian' },
  { id: 'ru', name: 'Russian' },
  { id: 'sm', name: 'Samoan' },
  { id: 'gd', name: 'Scots Gaelic' },
  { id: 'sr', name: 'Serbian' },
  { id: 'st', name: 'Sesotho' },
  { id: 'sn', name: 'Shona' },
  { id: 'sd', name: 'Sindhi' },
  { id: 'si', name: 'Sinhala (Sinhalese)' },
  { id: 'sk', name: 'Slovak' },
  { id: 'sl', name: 'Slovenian' },
  { id: 'so', name: 'Somali' },
  { id: 'es', name: 'Spanish' },
  { id: 'su', name: 'Sundanese' },
  { id: 'sw', name: 'Swahili' },
  { id: 'sv', name: 'Swedish' },
  { id: 'tl', name: 'Tagalog (Filipino)' },
  { id: 'tg', name: 'Tajik' },
  { id: 'ta', name: 'Tamil' },
  { id: 'tt', name: 'Tatar' },
  { id: 'te', name: 'Telugu' },
  { id: 'th', name: 'Thai' },
  { id: 'tr', name: 'Turkish' },
  { id: 'tk', name: 'Turkmen' },
  { id: 'uk', name: 'Ukrainian' },
  { id: 'ur', name: 'Urdu' },
  { id: 'ug', name: 'Uyghur' },
  { id: 'uz', name: 'Uzbek' },
  { id: 'vi', name: 'Vietnamese' },
  { id: 'cy', name: 'Welsh' },
  { id: 'xh', name: 'Xhosa' },
  { id: 'yi', name: 'Yiddish' },
  { id: 'yo', name: 'Yoruba' },
  { id: 'zu', name: 'Zulu' },
];

export const PROFICIENCY_LEVELS = [
  { id: 'beginner', name: 'Beginner' },
  { id: 'elementary', name: 'Elementary' },
  { id: 'intermediate', name: 'Intermediate' },
  { id: 'advanced', name: 'Advanced' },
  { id: 'fluent', name: 'Fluent' },
];

// Sample tags - these would normally be fetched from user data
export const SAMPLE_TAGS = [
  'Greetings',
  'Common phrases',
  'Food',
  'Travel',
  'Business',
  'Family',
  'Numbers',
  'Time',
  'Weather',
  'Shopping',
  'Verbs',
  'Nouns',
  'Adjectives',
  'Vocabulary',
  'Slang',
  'Idioms',
  'Beginner',
  'Intermediate',
  'Advanced',
  'Morning',
  'Evening',
  'Questions',
  'Expressions',
  'Farewells',
  'Introductions',
  'Learning',
  'Directions',
  'School',
  'Office',
  'Transportation',
  'Emergency',
  'Medical',
  'Dining',
  'Holidays',
  'Culture'
];

export const QUIZ_TYPES = [
  { 
    id: 'learned', 
    name: 'Only Learned Phrases', 
    description: 'Test your knowledge on the phrases you already learned',
    color: 'bg-green-500/20'
  },
  { 
    id: 'not-learned', 
    name: 'Only In Progress Phrases', 
    description: 'Practice phrases you still need to learn',
    color: 'bg-amber-500/20'
  },
  { 
    id: 'mixed', 
    name: 'All Phrases Mixed', 
    description: 'Both learned and in progress phrases',
    color: 'bg-primary/20'
  }
];

export const ADAPTIVE_TIME_PRESETS = [
  // Minimum time options
  { id: '1', name: '1 second', description: 'Minimum time per question' },
  { id: '2', name: '2 seconds', description: 'Minimum time per question' },
  { id: '3', name: '3 seconds', description: 'Minimum time per question' },
  { id: '4', name: '4 seconds', description: 'Minimum time per question' },
  { id: '5', name: '5 seconds', description: 'Minimum time per question' },
  { id: '6', name: '6 seconds', description: 'Minimum time per question' },
  { id: '7', name: '7 seconds', description: 'Minimum time per question' },
  { id: '8', name: '8 seconds', description: 'Minimum time per question' },
  { id: '9', name: '9 seconds', description: 'Minimum time per question' },
  { id: '10', name: '10 seconds', description: 'Minimum time per question' },
  
  // Starting time options
  { id: '15', name: '15 seconds', description: 'Default starting time' },
  { id: '20', name: '20 seconds', description: 'Default starting time' },
  
  // Maximum time options
  { id: '25', name: '25 seconds', description: 'Maximum time per question' },
  { id: '30', name: '30 seconds', description: 'Maximum time per question' },
  { id: '35', name: '35 seconds', description: 'Maximum time per question' },
  { id: '40', name: '40 seconds', description: 'Maximum time per question' },
  { id: '45', name: '45 seconds', description: 'Maximum time per question' },
];
